lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test

notifications:
  #slack: '<account>:<token>#development'
  email:
    recipients:
      - nirvana.carlos18@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $APIKEYHEROKU # desde heroku
  app: cguzman-store-backend
  on:
    repo: carlosguzmanbaquero/platzi-store-backend